### ISSUE TITLE
Flakiness detection not working properly with retry-tests-on-failure and test-iterations xcodebuild parameters

### ISSUE THREAD

**Issue by dcacenabes** [DataDog/dd-sdk-swift-testing#68] opened 2022-10-31 16:54 UTC
### Flakiness detection not working as expected

We are using a feature introduced in Xcode 13, automatic test retries. This can be invoked used passing the following parameters to xcodebuild:
```
-retry-tests-on-failure -test-iterations X
```
where X is the number of retries you want to run a test in case it fails. Here is an example of the xcresult this produces:
![Screenshot 2022-10-31 at 17 48 15](https://user-images.githubusercontent.com/3796899/199063167-4a05ba6f-1bdd-48d8-92eb-6ca1a094c3a1.png)

Currently, this test run does not trigger flaky test detection.
From DataDog UI:
![Screenshot 2022-10-31 at 17 51 02](https://user-images.githubusercontent.com/3796899/199063734-33ec2aa3-d0ee-4195-90ee-e9c15d07de02.png)
![Screenshot 2022-10-31 at 17 51 26](https://user-images.githubusercontent.com/3796899/199063825-2334d506-1d3e-469f-a870-7087a9227235.png)

I think that this case should be handled as a flaky test, since in the same run it was run multiple times and it failed twice and finally passed.
In the "How are flaky tests defined?" help section I see that: 
> Flaky tests are tests that exhibit both a passing and failing status across multiple test runs for the same commit. If you commit some code and run it through CI, and a test fails, and you run it through CI again and the test passes, that test is unreliable as proof of quality code.

Not sure, but it seems that the issue here is that it only takes into consideration different runs, and in this case we have only one run.

Is this expected behavior? It makes flakiness detection really bad for us. Is there anything we can do at the configuration level to make this work the way we want?

**Comment by nachoBonafonte** [comment] 2022-11-02 08:24
No, its not expected behaviour, and as you say it should be detected as a flaky test. Let me investigate what is happening and I will come back with more info.

**Comment by dcacenabes** [comment] 2022-11-02 09:15
By the way, I forgot to mention in my original report. I was running DatadogSDKTesting (2.1.2)

**Comment by nachoBonafonte** [comment] 2022-11-02 13:58
I have some more information: It is both a backend issue and also the way the information is shown, that is not very clear:
- There is nothing wrong on the testing framework or in you configuration, it is a backend issue and some backend developers are now working now on the issue. (might be a race condition due to the consecutive executions but still investigating)
- The test **is** `Flaky` and it is surely marked as such
- **This is the issue** - The backend fails to mark the test as `New Flaky`, which is why it is not shown in the table you have posted (which only shows `new flaky` tests)
- A `Flaky` test is also tagged as `New Flaky` or `Known Flaky`
- `New Flaky` are the test that started to show flakiness in the current commit, while `Known Flaky` are tests that showed flakiness in previous commits.
- The `commit view` only show a table with `New Flaky` while the `branch view` shows all flaky tests for a branch (new or known). To access the branch view from the `commit view` you must click on the branch name that is at the top of the page (it shows in grey with the branch icon).
- All `Flaky` tests should appear in the branch view
- If you click on the test, it will show the `Test Run View` where it will show some information about the  flakiness status (first time it flaked, and such).

I hope I explained it clearly, but TLDR - Its an issue on our side that we are working to solve soon, the test is stored as `Flaky` but backend fails to show it in the `New Flaky` table.

I will update the thread whenever I have more information

**Comment by nachoBonafonte** [comment] 2022-11-21 10:36
I am said that the issue is already fixed in the backend, the behaviour should be correct now. If you see something unexpected please let me know.

**Closed** 2023-01-03 09:14 UTC
